"""
Django settings for django_site project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
import logging.config
from os import getenv
import sys
from celery.schedules import crontab

from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = getenv(
    "SECRET_KEY", "django-insecure-fh_wan5bo5hvr=(7*y1jar%%a580e&mb_8n7i0lkskc^kl5hrp"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = getenv("DJANGO_DEBUG", "1") == "1"


ALLOWED_HOSTS = [
    "127.0.0.1",
    "0.0.0.0",
    "localhost",
] + getenv(
    "DJANGO_ALLOWED_HOSTS", ""
).split(",")


if not DEBUG:
    """Настройка для аутентификации, применяющаяся при развертывании на сервере"""
    # CSRF_TRUSTED_ORIGINS = getenv("DJANGO_DOMAIN", "").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "django_filters",
    "authentication.apps.AuthenticationConfig",
    "pilot.apps.PilotConfig",
    "responsible_person.apps.ResponsiblePersonConfig",
    "accompanied.apps.AccompaniedConfig",
    "report.apps.ReportConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "django_site.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "django_site.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

if DEBUG:
    print("--- Database is SqLite ---")

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    print("--- Database is PostgreSQL ---")

    POSTGRES_USER = getenv("POSTGRES_USER")
    POSTGRES_PASSWORD = getenv("POSTGRES_PASSWORD")
    POSTGRES_NAME = getenv("POSTGRES_NAME")
    POSTGRES_PORT = getenv("POSTGRES_PORT")

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": POSTGRES_NAME,
            "USER": POSTGRES_USER,
            "PASSWORD": POSTGRES_PASSWORD,
            "HOST": "postgres",
            "PORT": POSTGRES_PORT,
        }
    }

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}


# ============== Логирование ==============
LOGLEVEL = getenv("DJANGO_LOGLEVEL", "INFO")

logging.config.dictConfig(
    {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "verbose": {"format": "%(levelname)s %(asctime)s %(module)s %(message)s"},
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "formatter": "verbose",
            },
        },
        "loggers": {
            "": {
                "handlers": ["console"],
                "level": LOGLEVEL,
            },
        },
    }
)


# ============== Редиректы для аутентификации ==============
LOGIN_REDIRECT_URL = reverse_lazy("accompanied:accompanied_list")
LOGIN_URL = reverse_lazy("authentication:login")

# ============== Статика ==============
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# ============== Медиа ==============
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# ============== Настройка локальной папки для сохранения видео ==============
TMP_DIR = MEDIA_ROOT / "tmp"
os.makedirs(TMP_DIR, exist_ok=True)

# ============== Настройка swagger ==============
SPECTACULAR_SETTINGS = {
    "TITLE": "API for MAX bot",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}


# ============== Настройка REST FRAMEWORK ==============
REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
    ],
}


# ============== Настройка для медиа ==============
if not DEBUG:
    """S3 для медиа"""
    AWS_ACCESS_KEY_ID = getenv("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = getenv("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = getenv("AWS_STORAGE_BUCKET_NAME")

    AWS_S3_ENDPOINT_URL = "https://s3.twcstorage.ru"
    AWS_S3_REGION_NAME = "ru-1"
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = True
    AWS_QUERYSTRING_EXPIRE = 60 * 15

    # --- Настройки хранилищ ---
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "bucket_name": AWS_STORAGE_BUCKET_NAME,
                "region_name": AWS_S3_REGION_NAME,
                "access_key": AWS_ACCESS_KEY_ID,
                "secret_key": AWS_SECRET_ACCESS_KEY,
                "endpoint_url": AWS_S3_ENDPOINT_URL,
                "location": "media",
            },
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

# ============== Тестовые данные для пользвателя ==============
TEST_USER_DATA = {
    "username": "bob",
    "password": "pbkdf2_sha256$1500000$J3jZazSLjsck3Pops2gEQ2$OYiDmGMi7o7/SgW2I1i5LuucQeURKqTvBcTFTgo0CqA=",
}

# ==============  Настройки для размеров файлов ==============

MAX_PHOTO_SIZE = 5 * 1024 * 1024
MAX_VIDEO_SIZE = 50 * 1024 * 1024

# ============== Настройки Celery ==============
RABBITMQ_USER = getenv("RABBITMQ_USER")
RABBITMQ_PASSWORD = getenv("RABBITMQ_PASSWORD")

CELERY_BROKER_URL = f"amqp://{RABBITMQ_USER}:{RABBITMQ_PASSWORD}@rabbitmq:5672//"

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_IGNORE_RESULT = True
CELERY_TASK_EAGER_PROPAGATES = True

TESTING = "test" in sys.argv

if TESTING or DEBUG:
    """В режиме разработки задачи выполняются синхронно"""
    CELERY_TASK_ALWAYS_EAGER = True
else:
    CELERY_TASK_ALWAYS_EAGER = getenv("CELERY_TASK_ALWAYS_EAGER")

# ============== Настройка Celery-beat задачь ==============
CELERY_BEAT_SCHEDULE = {
    "remove-old-reports": {
        "task": "report.tasks.delete_old_reports",
        "schedule": crontab(minute=0, hour=3),
    },
}
