# Generated by Django 6.1.1 on 2026-09-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsiblePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('status', models.CharField(choices=[('parent', 'родитель'), ('guardian', 'опекун'), ('other', 'другое')], default='other', max_length=50, verbose_name='Статус ответственного лица по соотношению к сопровождаемому')),
                ('max_name', models.CharField(max_length=50, unique=True, verbose_name='Имя в MAX')),
                ('telephone', models.CharField(max_length=15, unique=True, verbose_name='Номер телефона')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
            ],
        ),
    ]
