# Generated by Django 6.1.1 on 2026-09-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsible_person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsibleperson',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Описание'),
        ),
    ]
