# Generated by Django 6.1.1 on 2026-09-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsible_person', '0002_alter_responsibleperson_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsibleperson',
            name='max_user_id',
            field=models.IntegerField(default=1, verbose_name='ID в MAX'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='responsibleperson',
            name='status',
            field=models.CharField(choices=[('parent', 'родитель'), ('guardian', 'опекун'), ('friend', 'друг'), ('other', 'другое')], default='other', max_length=50, verbose_name='Статус ответственного лица по соотношению к сопровождаемому'),
        ),
    ]
