# Generated by Django 6.1.1 on 2026-09-20 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responsible_person', '0003_responsibleperson_max_user_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsibleperson',
            options={'verbose_name': ('Профиль ответственного лица',), 'verbose_name_plural': ('Профили ответственных лиц',)},
        ),
    ]
