# Generated by Django 6.1.1 on 2026-09-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("responsible_person", "0004_alter_responsibleperson_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="responsibleperson",
            options={
                "verbose_name": "Профиль ответственного лица",
                "verbose_name_plural": "Профили ответственных лиц",
            },
        ),
    ]
