# Generated by Django 6.1.1 on 2026-10-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("responsible_person", "0005_alter_responsibleperson_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responsibleperson",
            name="max_name",
            field=models.CharField(
                blank=True, max_length=50, unique=True, verbose_name="Имя в MAX"
            ),
        ),
    ]
