# Generated by Django 6.1.1 on 2026-10-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("responsible_person", "0006_alter_responsibleperson_max_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responsibleperson",
            name="max_user_id",
            field=models.IntegerField(unique=True, verbose_name="ID в MAX"),
        ),
    ]
