# Generated by Django 6.1.1 on 2026-10-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("responsible_person", "0007_alter_responsibleperson_max_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responsibleperson",
            name="status",
            field=models.CharField(
                choices=[
                    ("родитель", "родитель"),
                    ("опекун", "опекун"),
                    ("друг", "друг"),
                    ("другое", "другое"),
                ],
                default="другое",
                max_length=50,
                verbose_name="Статус ответственного лица по соотношению к сопровождаемому",
            ),
        ),
    ]
