# Generated by Django 6.1.1 on 2026-10-05 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("responsible_person", "0009_alter_responsibleperson_max_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="responsibleperson",
            name="status",
        ),
    ]
