# Generated by Django 6.1.1 on 2026-09-21 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название отчета')),
                ('text', models.TextField(blank=True, verbose_name='Текст записи в отчете')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_notes', to='report.report', verbose_name='Отчет')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_notes', to=settings.AUTH_USER_MODEL, verbose_name='Автор отчета')),
            ],
            options={
                'verbose_name': 'Запись отчета',
                'verbose_name_plural': 'Записи отчетов',
            },
        ),
    ]
