# Generated by Django 6.1.1 on 2026-09-21 18:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_reportnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportNoteVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='report_videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='report.reportnote', verbose_name='Видео в записи')),
            ],
            options={
                'verbose_name': 'Видео запись',
                'verbose_name_plural': 'Видео записи',
            },
        ),
    ]
