# Generated by Django 6.1.1 on 2026-09-21 18:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_reportnotevideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportNotePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='report_photo/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='report.reportnote', verbose_name='Фото в записи')),
            ],
            options={
                'verbose_name': 'Фото записи',
                'verbose_name_plural': 'Фотографии записей',
            },
        ),
    ]
