# Generated by Django 6.1.1 on 2026-09-22 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_reportnotephoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportnote',
            name='report',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_notes', to='report.report', verbose_name='Отчет'),
        ),
        migrations.AlterField(
            model_name='reportnote',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_notes', to=settings.AUTH_USER_MODEL, verbose_name='Автор отчета'),
        ),
    ]
