# Generated by Django 6.1.1 on 2026-10-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0005_alter_reportnote_report_alter_reportnote_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportnotephoto",
            name="title",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reportnotevideo",
            name="title",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reportnotephoto",
            name="photo",
            field=models.FileField(upload_to="report_videos/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="reportnotevideo",
            name="video",
            field=models.FileField(upload_to="report_videos/%Y/%m/%d/"),
        ),
    ]
