# Generated by Django 6.1.1 on 2026-10-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0006_reportnotephoto_title_reportnotevideo_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportnotevideo",
            name="status",
            field=models.CharField(default="pending", max_length=50),
        ),
    ]
