# Generated by Django 6.1.1 on 2026-10-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0007_reportnotevideo_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportnotevideo",
            name="video",
            field=models.FileField(upload_to=""),
        ),
    ]
