# Generated by Django 6.1.1 on 2026-10-06 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0008_alter_reportnotevideo_video"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reportnotephoto",
            options={
                "verbose_name": "Фото заметки отчета",
                "verbose_name_plural": "Фотографии заметки отчета",
            },
        ),
        migrations.AlterModelOptions(
            name="reportnotevideo",
            options={
                "verbose_name": "Видео запись заметки отчета",
                "verbose_name_plural": "Видео записи заметки отчета",
            },
        ),
    ]
