# Generated by Django 6.1.1 on 2026-10-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0009_alter_reportnotephoto_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportnotephoto",
            name="photo",
            field=models.FileField(upload_to="report_photo/%Y/%m/%d/"),
        ),
    ]
