# Generated by Django 6.1.1 on 2026-09-15 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=15, unique=True, verbose_name='Телефон')),
                ('max_name', models.CharField(blank=True, max_length=50, verbose_name='Имя в MAX')),
                ('vk_name', models.CharField(blank=True, max_length=50, verbose_name='Имя в VK')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_pilot', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
