# Generated by Django 6.1.1 on 2026-09-20 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('region', models.CharField(blank=True, max_length=255, verbose_name='Регион')),
            ],
            options={
                'verbose_name': ('Населенный пункт',),
                'verbose_name_plural': ('Населенные пункты',),
            },
        ),
        migrations.AlterModelOptions(
            name='profilepilot',
            options={'verbose_name': ('Профиль пилота',), 'verbose_name_plural': ('Профили пилотов',)},
        ),
        migrations.AddField(
            model_name='profilepilot',
            name='work_arieas',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profilepilot',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_pilot', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='profilepilot',
            name='settlements',
            field=models.ManyToManyField(related_name='accompanied', to='pilot.settlement', verbose_name='Населённые пункты'),
        ),
    ]
