# Generated by Django 6.1.1 on 2026-09-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0002_settlement_alter_profilepilot_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settlement',
            name='region',
        ),
        migrations.AlterField(
            model_name='settlement',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название населенного пункта'),
        ),
    ]
