# Generated by Django 6.1.1 on 2026-09-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0003_remove_settlement_region_alter_settlement_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepilot',
            name='settlements',
            field=models.ManyToManyField(related_name='profile_pilot', to='pilot.settlement', verbose_name='Населённые пункты'),
        ),
    ]
