# Generated by Django 6.1.1 on 2026-09-21 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0004_alter_profilepilot_settlements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepilot',
            name='work_arieas',
        ),
    ]
