# Generated by Django 6.1.1 on 2026-09-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pilot", "0005_remove_profilepilot_work_arieas"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profilepilot",
            options={
                "verbose_name": "Профиль пилота",
                "verbose_name_plural": "Профили пилотов",
            },
        ),
        migrations.AlterModelOptions(
            name="settlement",
            options={
                "verbose_name": "Населенный пункт",
                "verbose_name_plural": "Населенные пункты",
            },
        ),
    ]
