# Generated by Django 6.1.1 on 2026-10-08 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pilot", "0006_alter_profilepilot_options_alter_settlement_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilepilot",
            name="file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="pilots/",
                validators=[
                    django.core.validators.FileExtensionValidator(["jpg", "png"])
                ],
            ),
        ),
    ]
