# Generated by Django 6.1.1 on 2026-10-08 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pilot", "0007_profilepilot_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profilepilot",
            old_name="file",
            new_name="preview",
        ),
    ]
