# Generated by Django 6.1.1 on 2026-09-16 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pilot', '0001_initial'),
        ('responsible_person', '0002_alter_responsibleperson_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accompanied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='accompanies/', verbose_name='Фото сопровождаемого')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('date_birth', models.DateField(verbose_name='Дата рождения')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Описание сопровождаемого')),
                ('health_problems', models.TextField(max_length=800, verbose_name='Проблемы со здоровьем')),
                ('tasks', models.TextField(max_length=800, verbose_name='Задачи пилота')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('pilots', models.ManyToManyField(related_name='accompanied', to='pilot.profilepilot')),
                ('responsible_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='responsible_person.responsibleperson')),
            ],
        ),
    ]
