# Generated by Django 6.1.1 on 2026-09-20 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accompanied', '0001_initial'),
        ('pilot', '0001_initial'),
        ('responsible_person', '0003_responsibleperson_max_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accompanied',
            name='pilots',
            field=models.ManyToManyField(blank=True, related_name='accompanied', to='pilot.profilepilot', verbose_name='Пилоты'),
        ),
        migrations.AlterField(
            model_name='accompanied',
            name='responsible_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='responsible_person.responsibleperson', verbose_name='Ответственное лицо'),
        ),
    ]
