# Generated by Django 6.1.1 on 2026-09-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accompanied', '0002_alter_accompanied_pilots_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accompanied',
            options={'verbose_name': ('Профиль сопровождаемого',), 'verbose_name_plural': ('Профили сопровождаемых',)},
        ),
        migrations.AlterField(
            model_name='accompanied',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Пользователь активен'),
        ),
    ]
