# Generated by Django 6.1.1 on 2026-10-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accompanied", "0003_alter_accompanied_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accompanied",
            options={
                "verbose_name": "Профиль сопровождаемого",
                "verbose_name_plural": "Профили сопровождаемых",
            },
        ),
    ]
