# Generated by Django 6.1.1 on 2026-10-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accompanied", "0004_alter_accompanied_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="accompanied",
            name="status",
            field=models.CharField(
                choices=[
                    ("родитель", "родитель"),
                    ("опекун", "опекун"),
                    ("друг", "друг"),
                    ("другое", "другое"),
                ],
                default="другое",
                max_length=50,
                verbose_name="Статус ответственного лица по соотношению к сопровождаемому",
            ),
        ),
    ]
