# Generated by Django 6.1.1 on 2026-10-06 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accompanied", "0005_accompanied_status"),
        ("responsible_person", "0010_remove_responsibleperson_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accompanied",
            name="responsible_person",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accompanied_individuals",
                to="responsible_person.responsibleperson",
                verbose_name="Ответственное лицо",
            ),
        ),
    ]
