name: CI Check

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Install python dependencies
        run: pip install -r $GITHUB_WORKSPACE/apps/django_site/requirements.txt

      - name: Check formating code
        run: black --check $GITHUB_WORKSPACE/apps/django_site/
